# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'Ubuntu-16.04'
  #vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
# - task: Npm@1
#   inputs:
#     command: install
#     workingDir: 'solution/SurveyMe/SurveyMe.SPA/Client/'
#   displayName: 'npm install'

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'
  displayName: 'nuget restore'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '**/*SurveyMe.sln'
    configuration: '$(buildConfiguration)'
  displayName: 'sln build'

- task: Npm@1
  inputs:
    command: install
    workingDir: 'solution/SurveyMe/SurveyMe.SPA/Client/'
  displayName: 'npm install'

- task: Npm@1
  inputs:
    command: custom
    customCommand: sudo install -g @angular/cli
  displayName: 'install angularCli'

- task: Npm@1
  inputs:
    command: custom
    customCommand: run build-prod
    workingDir: 'solution/SurveyMe/SurveyMe.SPA/Client/'
  displayName: 'npm build'
