# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:  
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'
  displayName: 'nuget restore'
    
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '**/*.sln'
    configuration: '$(buildConfiguration)'    
  displayName: 'build'
    
